ALTER TABLE traffic_cursors ADD COLUMN provider_type TEXT NOT NULL DEFAULT '';
ALTER TABLE traffic_cursors ADD COLUMN instance_version TEXT NOT NULL DEFAULT '';
CREATE TABLE traffic_provenance(identity_id INTEGER PRIMARY KEY REFERENCES identities(id), provider_type TEXT NOT NULL,metric_scope TEXT NOT NULL,capability_status TEXT NOT NULL,collected_at TEXT NOT NULL,instance_version TEXT NOT NULL,config_revision TEXT NOT NULL,source_upload_name TEXT NOT NULL,source_download_name TEXT NOT NULL,raw_upload INTEGER NOT NULL,raw_download INTEGER NOT NULL,traffic_direction TEXT NOT NULL,mapped INTEGER NOT NULL,coverage TEXT NOT NULL);
CREATE TABLE native_connection_cursors(instance_id INTEGER NOT NULL REFERENCES instances(id),epoch_id TEXT NOT NULL,connection_id TEXT NOT NULL,inbound_tag TEXT NOT NULL,user_key TEXT NOT NULL,raw_upload INTEGER NOT NULL,raw_download INTEGER NOT NULL,observed_at TEXT NOT NULL,PRIMARY KEY(instance_id,epoch_id,connection_id));
CREATE TABLE native_user_totals(instance_id INTEGER NOT NULL REFERENCES instances(id),inbound_tag TEXT NOT NULL,user_key TEXT NOT NULL,upload INTEGER NOT NULL,download INTEGER NOT NULL,PRIMARY KEY(instance_id,inbound_tag,user_key));
CREATE TABLE core_asset_states(instance_id INTEGER NOT NULL REFERENCES instances(id),inbound_tag TEXT NOT NULL,email TEXT NOT NULL,online_state TEXT NOT NULL,online_count INTEGER,online_kind TEXT NOT NULL,online_basis TEXT NOT NULL,checked_at TEXT NOT NULL,PRIMARY KEY(instance_id,inbound_tag,email));
CREATE TABLE provider_observations(instance_id INTEGER NOT NULL REFERENCES instances(id),provider_type TEXT NOT NULL,metric_scope TEXT NOT NULL,capability_status TEXT NOT NULL,collected_at TEXT NOT NULL,instance_version TEXT NOT NULL,config_revision TEXT NOT NULL,summary_json TEXT NOT NULL,PRIMARY KEY(instance_id,provider_type,metric_scope));
CREATE TABLE config_operations(id INTEGER PRIMARY KEY,instance_id INTEGER NOT NULL REFERENCES instances(id),operation TEXT NOT NULL,inbound_tag TEXT NOT NULL,old_revision TEXT NOT NULL,new_revision TEXT NOT NULL,apply_status TEXT NOT NULL,created_at TEXT NOT NULL,summary TEXT NOT NULL);
CREATE TABLE direction_audits(id INTEGER PRIMARY KEY,created_at TEXT NOT NULL,instance_id INTEGER NOT NULL,affected_records INTEGER NOT NULL,status TEXT NOT NULL,backup_path TEXT NOT NULL DEFAULT '');
