// Read-only wire projection of Xray-core v26.3.27 (MPL-2.0).
// Field numbers match upstream; no mutation RPCs are generated.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: internal/proto/xrayhandler/handler.proto

package xrayhandlerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypedAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedAccount) Reset() {
	*x = TypedAccount{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedAccount) ProtoMessage() {}

func (x *TypedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedAccount.ProtoReflect.Descriptor instead.
func (*TypedAccount) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{0}
}

func (x *TypedAccount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypedAccount) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Account       *TypedAccount          `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAccount() *TypedAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

type Inbound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inbound) Reset() {
	*x = Inbound{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inbound) ProtoMessage() {}

func (x *Inbound) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inbound.ProtoReflect.Descriptor instead.
func (*Inbound) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{2}
}

func (x *Inbound) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListInboundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOnlyTags    bool                   `protobuf:"varint,1,opt,name=isOnlyTags,proto3" json:"isOnlyTags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboundsRequest) Reset() {
	*x = ListInboundsRequest{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboundsRequest) ProtoMessage() {}

func (x *ListInboundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboundsRequest.ProtoReflect.Descriptor instead.
func (*ListInboundsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{3}
}

func (x *ListInboundsRequest) GetIsOnlyTags() bool {
	if x != nil {
		return x.IsOnlyTags
	}
	return false
}

type ListInboundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inbounds      []*Inbound             `protobuf:"bytes,1,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboundsResponse) Reset() {
	*x = ListInboundsResponse{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboundsResponse) ProtoMessage() {}

func (x *ListInboundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboundsResponse.ProtoReflect.Descriptor instead.
func (*ListInboundsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{4}
}

func (x *ListInboundsResponse) GetInbounds() []*Inbound {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type GetInboundUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUserRequest) Reset() {
	*x = GetInboundUserRequest{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserRequest) ProtoMessage() {}

func (x *GetInboundUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserRequest.ProtoReflect.Descriptor instead.
func (*GetInboundUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{5}
}

func (x *GetInboundUserRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetInboundUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetInboundUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUserResponse) Reset() {
	*x = GetInboundUserResponse{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserResponse) ProtoMessage() {}

func (x *GetInboundUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserResponse.ProtoReflect.Descriptor instead.
func (*GetInboundUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{6}
}

func (x *GetInboundUserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetInboundUsersCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUsersCountResponse) Reset() {
	*x = GetInboundUsersCountResponse{}
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUsersCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUsersCountResponse) ProtoMessage() {}

func (x *GetInboundUsersCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_xrayhandler_handler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUsersCountResponse.ProtoReflect.Descriptor instead.
func (*GetInboundUsersCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_xrayhandler_handler_proto_rawDescGZIP(), []int{7}
}

func (x *GetInboundUsersCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_internal_proto_xrayhandler_handler_proto protoreflect.FileDescriptor

const file_internal_proto_xrayhandler_handler_proto_rawDesc = "" +
	"\n" +
	"(internal/proto/xrayhandler/handler.proto\x12\x19xray.app.proxyman.command\"8\n" +
	"\fTypedAccount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"u\n" +
	"\x04User\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12A\n" +
	"\aaccount\x18\x03 \x01(\v2'.xray.app.proxyman.command.TypedAccountR\aaccount\"\x1b\n" +
	"\aInbound\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"5\n" +
	"\x13ListInboundsRequest\x12\x1e\n" +
	"\n" +
	"isOnlyTags\x18\x01 \x01(\bR\n" +
	"isOnlyTags\"V\n" +
	"\x14ListInboundsResponse\x12>\n" +
	"\binbounds\x18\x01 \x03(\v2\".xray.app.proxyman.command.InboundR\binbounds\"?\n" +
	"\x15GetInboundUserRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"O\n" +
	"\x16GetInboundUserResponse\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.xray.app.proxyman.command.UserR\x05users\"4\n" +
	"\x1cGetInboundUsersCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xfd\x02\n" +
	"\x0eHandlerService\x12o\n" +
	"\fListInbounds\x12..xray.app.proxyman.command.ListInboundsRequest\x1a/.xray.app.proxyman.command.ListInboundsResponse\x12v\n" +
	"\x0fGetInboundUsers\x120.xray.app.proxyman.command.GetInboundUserRequest\x1a1.xray.app.proxyman.command.GetInboundUserResponse\x12\x81\x01\n" +
	"\x14GetInboundUsersCount\x120.xray.app.proxyman.command.GetInboundUserRequest\x1a7.xray.app.proxyman.command.GetInboundUsersCountResponseB?Z=traffic-manager-lite/internal/proto/xrayhandler;xrayhandlerpbb\x06proto3"

var (
	file_internal_proto_xrayhandler_handler_proto_rawDescOnce sync.Once
	file_internal_proto_xrayhandler_handler_proto_rawDescData []byte
)

func file_internal_proto_xrayhandler_handler_proto_rawDescGZIP() []byte {
	file_internal_proto_xrayhandler_handler_proto_rawDescOnce.Do(func() {
		file_internal_proto_xrayhandler_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_xrayhandler_handler_proto_rawDesc), len(file_internal_proto_xrayhandler_handler_proto_rawDesc)))
	})
	return file_internal_proto_xrayhandler_handler_proto_rawDescData
}

var file_internal_proto_xrayhandler_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_xrayhandler_handler_proto_goTypes = []any{
	(*TypedAccount)(nil),                 // 0: xray.app.proxyman.command.TypedAccount
	(*User)(nil),                         // 1: xray.app.proxyman.command.User
	(*Inbound)(nil),                      // 2: xray.app.proxyman.command.Inbound
	(*ListInboundsRequest)(nil),          // 3: xray.app.proxyman.command.ListInboundsRequest
	(*ListInboundsResponse)(nil),         // 4: xray.app.proxyman.command.ListInboundsResponse
	(*GetInboundUserRequest)(nil),        // 5: xray.app.proxyman.command.GetInboundUserRequest
	(*GetInboundUserResponse)(nil),       // 6: xray.app.proxyman.command.GetInboundUserResponse
	(*GetInboundUsersCountResponse)(nil), // 7: xray.app.proxyman.command.GetInboundUsersCountResponse
}
var file_internal_proto_xrayhandler_handler_proto_depIdxs = []int32{
	0, // 0: xray.app.proxyman.command.User.account:type_name -> xray.app.proxyman.command.TypedAccount
	2, // 1: xray.app.proxyman.command.ListInboundsResponse.inbounds:type_name -> xray.app.proxyman.command.Inbound
	1, // 2: xray.app.proxyman.command.GetInboundUserResponse.users:type_name -> xray.app.proxyman.command.User
	3, // 3: xray.app.proxyman.command.HandlerService.ListInbounds:input_type -> xray.app.proxyman.command.ListInboundsRequest
	5, // 4: xray.app.proxyman.command.HandlerService.GetInboundUsers:input_type -> xray.app.proxyman.command.GetInboundUserRequest
	5, // 5: xray.app.proxyman.command.HandlerService.GetInboundUsersCount:input_type -> xray.app.proxyman.command.GetInboundUserRequest
	4, // 6: xray.app.proxyman.command.HandlerService.ListInbounds:output_type -> xray.app.proxyman.command.ListInboundsResponse
	6, // 7: xray.app.proxyman.command.HandlerService.GetInboundUsers:output_type -> xray.app.proxyman.command.GetInboundUserResponse
	7, // 8: xray.app.proxyman.command.HandlerService.GetInboundUsersCount:output_type -> xray.app.proxyman.command.GetInboundUsersCountResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_xrayhandler_handler_proto_init() }
func file_internal_proto_xrayhandler_handler_proto_init() {
	if File_internal_proto_xrayhandler_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_xrayhandler_handler_proto_rawDesc), len(file_internal_proto_xrayhandler_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_xrayhandler_handler_proto_goTypes,
		DependencyIndexes: file_internal_proto_xrayhandler_handler_proto_depIdxs,
		MessageInfos:      file_internal_proto_xrayhandler_handler_proto_msgTypes,
	}.Build()
	File_internal_proto_xrayhandler_handler_proto = out.File
	file_internal_proto_xrayhandler_handler_proto_goTypes = nil
	file_internal_proto_xrayhandler_handler_proto_depIdxs = nil
}
