const {spawnSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),suffix=Date.now().toString(36),project='tml-compose-'+suffix,network=project+'-network',name=project+'-app',dir=path.join(root,'.tools',project);
fs.mkdirSync(dir,{recursive:true});for(const child of ['data','backups','configs','traffic-manager-lite'])fs.mkdirSync(path.join(dir,child));
fs.copyFileSync(path.join(root,'deploy/docker-compose.yml'),path.join(dir,'docker-compose.yml'));
fs.writeFileSync(path.join(dir,'.env'),'TML_ADMIN_PASSWORD=compose-fixture-password-123456\nTML_SECURE_COOKIE=false\nTML_DB_PATH=/app/data/traffic.db\nTML_BACKUP_DIR=/app/backups\nTML_CONFIG_ROOT=/app/configs\n');
fs.writeFileSync(path.join(dir,'override.yml'),`services:\n  traffic-manager-lite:\n    image: traffic-manager-lite:verify\n    container_name: ${name}\n    ports: !override\n      - "127.0.0.1::8080"\n    healthcheck:\n      interval: 1s\n      start_period: 1s\nnetworks:\n  my-network:\n    name: ${network}\n`);
function docker(...args){const r=spawnSync('docker',args,{encoding:'utf8',windowsHide:true});if(r.status!==0)throw new Error(r.stderr||r.stdout);return r.stdout.trim()}
function compose(...args){return docker('compose','--project-directory',dir,'-p',project,'-f',path.join(dir,'docker-compose.yml'),'-f',path.join(dir,'override.yml'),...args)}
let base='';const headers={Authorization:'Basic '+Buffer.from('admin:compose-fixture-password-123456').toString('base64'),'Content-Type':'application/json'};
async function ready(){for(let i=0;i<50;i++){try{if((await fetch(base+'/api/v1/health')).ok)return}catch{}await new Promise(r=>setTimeout(r,200))}throw new Error('compose health timeout')}
async function main(){docker('network','create','--label','tml.test=true',network);compose('config','--quiet');compose('up','-d','--no-build');base='http://'+docker('port',name,'8080/tcp');await ready();const server=await fetch(base+'/api/v1/servers',{method:'POST',headers,body:JSON.stringify({name:'Compose bind-mount test',address:'localhost',enabled:true})});assert.equal(server.status,200);const backup=await fetch(base+'/api/v1/maintenance/backup',{method:'POST',headers,body:'{}'});assert.equal(backup.status,200);compose('restart','traffic-manager-lite');base='http://'+docker('port',name,'8080/tcp');await ready();const servers=await(await fetch(base+'/api/v1/servers',{headers})).json();assert.equal(servers[0].name,'Compose bind-mount test');assert.ok(fs.existsSync(path.join(dir,'data/traffic.db')));assert.ok(fs.readdirSync(path.join(dir,'backups')).some(x=>x.endsWith('.db')));for(let i=0;i<30;i++){if(docker('inspect','--format','{{.State.Health.Status}}',name)==='healthy')break;await new Promise(r=>setTimeout(r,500))}assert.equal(docker('inspect','--format','{{.State.Health.Status}}',name),'healthy');console.log('PASS: provided Compose deployment layout, external network, nonroot bind-mounted SQLite/backup directories, health and data persistence after restart');fs.writeFileSync(path.join(root,'dist/compose-smoke-result.json'),JSON.stringify({passed:true,project,checks:['compose_template','external_network','host_data_bind','host_backup_bind','restart_persistence','health']}));}
main().catch(e=>{console.error(e);try{console.error(compose('logs','--tail','30'))}catch{}process.exitCode=1}).finally(()=>{try{compose('down','--timeout','5')}catch{}try{docker('network','rm',network)}catch{}});
