/* Actual official four-core APIs. Temporary configurations, no fixture traffic. */
const {spawn,execFileSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.TML_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'tml-four-core-ui-')),out=path.join(root,'dist','ui-verification'),processes=[];fs.mkdirSync(out,{recursive:true});let browser,dockerName;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function udpPort(){return new Promise((resolve,reject)=>{const socket=require('node:dgram').createSocket('udp4');socket.once('error',reject);socket.bind(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p))})})}
async function port(){return new Promise(r=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p))})})}
function start(binary,args,env={}){const process=spawn(binary,args,{windowsHide:true,cwd:tmp,env:{...global.process.env,...env}});let logs='';process.stderr.on('data',b=>logs+=b);process.stdout.on('data',b=>logs+=b);process.logs=()=>logs;processes.push(process);return process}
function write(name,data){const p=path.join(tmp,name);fs.writeFileSync(p,typeof data==='string'?data:JSON.stringify(data),{mode:0o600});return p}
function evidence(binary,kind,endpoint,config){const output=execFileSync(binary,['version'],{encoding:'utf8',windowsHide:true});const proof={core_type:kind,api_endpoint:endpoint,output,observed_at:new Date().toISOString(),config_sha256:crypto.createHash('sha256').update(fs.readFileSync(config)).digest('hex'),method:kind==='xray'?'controlled_xray_version':'controlled_core_version'};if(kind==='xray')proof.output=output.split(/\r?\n/)[0];fs.writeFileSync(config+'.version.json',JSON.stringify(proof),{mode:0o600})}
async function main(){
 const binaries={xray:process.env.TML_TEST_XRAY,hysteria2:process.env.TML_TEST_HYSTERIA2,singbox:process.env.TML_TEST_SINGBOX_DIAGNOSTICS,v2fly:process.env.TML_TEST_V2FLY};for(const b of Object.values(binaries))assert.ok(b,'four verified binaries required');
 const cert=path.join(tmp,'cert.pem'),key=path.join(tmp,'key.pem'),openssl=process.env.TML_TEST_OPENSSL||(process.platform==='win32'?'C:/Program Files/Git/usr/bin/openssl.exe':'openssl');execFileSync(openssl,['req','-x509','-newkey','rsa:2048','-nodes','-days','1','-subj','/CN=localhost','-keyout',key,'-out',cert],{stdio:'ignore',windowsHide:true});
 const instances=[],credentials=[],secret='isolated-api-secret-never-shown',clashSecret='isolated-clash-secret-independent';credentials.push(secret,clashSecret);
 for(const kind of ['xray','hysteria2','singbox','v2fly']){
  const apiPort=await port(),inbound=kind==='hysteria2'?await udpPort():await port();let endpoint='localhost:'+apiPort,config,control='',clash='';
  const users=Array.from({length:10},(_,n)=>({name:'client-'+n,email:'client-'+n,uuid:crypto.randomUUID()}));credentials.push(...users.map(u=>u.uuid));
  if(kind==='hysteria2'){endpoint='http://localhost:'+apiPort;const pairs=users.map((u,n)=>'    '+u.name+': real-test-password-'+n).join('\n');config=write('hy.yaml',`listen: 127.0.0.1:${inbound}\ntls:\n  cert: ${cert.replaceAll('\\','/')}\n  key: ${key.replaceAll('\\','/')}\nauth:\n  type: userpass\n  userpass:\n${pairs}\ntrafficStats:\n  listen: 127.0.0.1:${apiPort}\n  secret: ${secret}\n`);start(binaries[kind],['server','-c',config]);}
  else if(kind==='singbox'){control=endpoint;const cp=await port();clash='http://localhost:'+cp;const docker=!!process.env.TML_TEST_DOCKER_SINGBOX_IMAGE,listen=docker?'0.0.0.0':'127.0.0.1',certificate=docker?'/configs/cert.pem':cert,privateKey=docker?'/configs/key.pem':key;config=write('singbox.json',{log:{level:'error'},inbounds:[{type:'vless',tag:'vless-users',listen,listen_port:inbound,users:users.map(u=>({name:u.name,uuid:u.uuid}))},{type:'hysteria2',tag:'hy-users',listen,listen_port:await udpPort(),users:[{name:'client-0',password:'isolated-hy-password'}],tls:{enabled:true,certificate_path:certificate,key_path:privateKey}},{type:'anytls',tag:'anytls-users',listen,listen_port:await port(),users:[{name:'client-0',password:'isolated-anytls-password'}],tls:{enabled:true,certificate_path:certificate,key_path:privateKey}}],outbounds:[{type:'direct',tag:'direct'}],services:[{type:'api',listen,listen_port:apiPort,secret,dashboard:false}],experimental:{clash_api:{external_controller:listen+':'+cp,secret:clashSecret}}});if(docker){dockerName='tml-core-ui-'+Date.now();execFileSync('docker',['run','-d','--name',dockerName,'--read-only','--cap-drop','ALL','--mount','type=bind,source='+tmp+',target=/configs,readonly','-p','127.0.0.1:'+apiPort+':'+apiPort,'-p','127.0.0.1:'+cp+':'+cp,process.env.TML_TEST_DOCKER_SINGBOX_IMAGE,'run','-c','/configs/singbox.json'],{stdio:'pipe',windowsHide:true})}else start(binaries[kind],['run','-c',config]);}
  else{const xray=kind==='xray';config=write(kind+'.json',{log:{loglevel:'error'},api:{tag:'api',services:xray?['HandlerService','StatsService']:['HandlerService','StatsService','LoggerService','ReflectionService']},stats:{},policy:{levels:{'0':{statsUserUplink:true,statsUserDownlink:true}}},inbounds:[{tag:'users',listen:'127.0.0.1',port:inbound,protocol:xray?'vless':'vmess',settings:{clients:users.map(u=>({email:u.email,id:u.uuid})),...(xray?{decryption:'none'}:{})}},{tag:'api',listen:'127.0.0.1',port:apiPort,protocol:'dokodemo-door',settings:{address:'127.0.0.1'}}],outbounds:[{protocol:'freedom',tag:'direct'}],routing:{rules:[{type:'field',inboundTag:['api'],outboundTag:'api'}]}});start(binaries[kind],['run','-c',config]);}
  evidence(binaries[kind],kind,endpoint,config);instances.push({test_inbound:inbound,name:'官方 '+kind,core_type:kind,api_endpoint:endpoint,control_endpoint:control,clash_endpoint:clash,clash_secret:kind==='singbox'?clashSecret:'',api_secret:kind==='hysteria2'||kind==='singbox'?secret:'',config_path:config,enabled:true});
 }
 let agentEnv={};if(dockerName){const agentPort=await port(),agentToken='isolated-host-agent-token-at-least-32-chars';const tokenFile=write('agent-token',agentToken),sb=instances.find(i=>i.core_type==='singbox'),targets=write('agent-targets.json',[{instance_id:3,container:dockerName,host_config:sb.config_path,container_config:'/configs/singbox.json',native_endpoint:sb.control_endpoint,api_secret:sb.api_secret}]);start(path.join(root,'dist','tml-core-agent'+(process.platform==='win32'?'.exe':'')),['-listen','127.0.0.1:'+agentPort,'-token-file',tokenFile,'-targets',targets,'-state-dir',path.join(tmp,'agent-private')]);agentEnv={TML_CORE_AGENT_URL:'http://127.0.0.1:'+agentPort,TML_CORE_AGENT_TOKEN:agentToken};}
 const httpPort=await port(),base='http://127.0.0.1:'+httpPort,password='isolated-real-ui-admin-password';const manager=start(path.join(root,'dist','traffic-manager-lite'+(process.platform==='win32'?'.exe':'')),[],{...agentEnv,TML_LISTEN:'127.0.0.1:'+httpPort,TML_DB_PATH:path.join(tmp,'traffic.db'),TML_CONFIG_ROOT:tmp,TML_BACKUP_DIR:path.join(tmp,'backups'),TML_ADMIN_PASSWORD:password,TML_SECURE_COOKIE:'false',TML_COLLECT_INTERVAL:'1h',TML_ALLOWED_TARGETS:''});
 async function api(route,method='GET',body){const r=await fetch(base+'/api/v1/'+route,{method,headers:{Authorization:'Basic '+Buffer.from('admin:'+password).toString('base64'),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await r.json();assert.ok(r.ok,route+': '+JSON.stringify(result));return result}
 for(let n=0;n<100;n++){try{if((await fetch(base+'/api/v1/health')).ok)break}catch{}await sleep(100)};assert.ok((await fetch(base+'/api/v1/health')).ok,manager.logs());await api('servers','POST',{name:'真实核心隔离验收',address:'localhost',enabled:true});
 for(const instance of instances){instance.server_id=1;const{id}=await api('instances','POST',Object.fromEntries(Object.entries(instance).filter(([k])=>!k.startsWith('test_'))));instance.id=id;for(let n=0;n<100;n++){const history=await api('instances/'+id+'/diagnostics/history');if(history.length)break;await sleep(100)};try{await api('instances/'+id+'/collect','POST',{})}catch(e){console.error('Sanitized diagnostic',await api('instances/'+id+'/diagnostics'));console.error('Core exits',processes.map(p=>p.exitCode));throw e};const assets=await api('instances/'+id+'/clients');assert.equal(assets.filter(c=>c.present&&c.source!=='config_file').length+(instance.core_type==='xray'?0:assets.filter(c=>c.present).length),instance.core_type==='singbox'?12:10);const report=await api('instances/'+id+'/diagnostics');assert.ok(report.version!=='Unknown','actual evidence/version not detected');assert.equal(report.connected,'Available');const serialized=JSON.stringify(report);for(const credential of credentials)assert.ok(!serialized.includes(credential),'credential leaked');}
 browser=await chromium.launch({headless:true});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('[name=password]').fill(password);await page.getByRole('button',{name:'登录管理后台'}).click();await page.waitForURL(base+'/');await page.goto(base+'/#instances');await page.getByRole('button',{name:'API 诊断',exact:true}).first().waitFor();assert.equal(await page.getByRole('button',{name:'API 诊断',exact:true}).count(),4);assert.equal(await page.getByRole('button',{name:'检测 API',exact:true}).count(),4);if(dockerName)await require('./managed-config-e2e.cjs')({api,page,base,instance:instances.find(i=>i.core_type==='singbox'),out});const hy=instances.find(i=>i.core_type==='hysteria2');hy.test_base=base;await require('./hysteria-direction.cjs')({instance:hy,binary:binaries.hysteria2,start,write,api,page,out});await page.goto(base+'/#diagnostics');await page.getByRole('heading',{name:'核心 API 诊断',exact:true}).waitFor();
 for(const width of [360,768,1440]){await page.setViewportSize({width,height:1000});for(const instance of instances){await page.locator('#diagnostic-core').selectOption(instance.core_type);await page.locator('#diagnostic-instance').selectOption('');await page.getByRole('button',{name:'查询',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('[data-action=diagnose]').length===1);await page.getByRole('button',{name:'立即诊断',exact:true}).waitFor();await page.getByRole('button',{name:'立即诊断',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('只读诊断完成'));await page.getByRole('button',{name:'查看诊断历史',exact:true}).click();await page.locator('#diagnostic-history-'+instance.id+' p').first().waitFor();await page.screenshot({path:path.join(out,'core-before-layout-'+instance.core_type+'-'+width+'.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'layout overflow '+instance.core_type+' '+width+' '+JSON.stringify(await page.evaluate(()=>Array.from(document.querySelectorAll('#content *')).filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,8).map(e=>({tag:e.tagName,class:e.className,text:e.textContent.slice(0,100),right:e.getBoundingClientRect().right})))));await page.screenshot({path:path.join(out,'core-diagnostics-real-'+instance.core_type+'-'+width+'.png'),fullPage:true});}}
 assert.deepEqual(errors,[]);console.log('PASS: four actual official cores; complete offline assets; actual versions; independent secrets; all diagnostic buttons; core filters/manual/history; 12 core+viewport checks; credential redaction');
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();for(const p of processes.reverse()){if(p.exitCode===null){p.kill();await new Promise(r=>{p.once('exit',r);setTimeout(r,2000)})}}if(dockerName)execFileSync('docker',['rm','-f',dockerName],{stdio:'ignore',windowsHide:true});fs.rmSync(tmp,{recursive:true,force:true})});
