/* Browser integration tests. Fixture APIs are confined to a temporary test database. */
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.TML_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'tml-e2e-')),output=path.join(root,'dist','ui-verification');fs.mkdirSync(output,{recursive:true});fs.mkdirSync(path.join(tmp,'configs'));
fs.writeFileSync(path.join(tmp,'configs','hy.yaml'),'listen: :443\nauth:\n  type: userpass\n  userpass:\n    alice: fixture-password\n');
const password='e2e-fixture-password-123456';let counter=0,browser,backend;const failures=[];let logs='';
const fixture=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.end(req.url==='/traffic'?JSON.stringify({alice:{tx:counter*2000,rx:counter*1000}}):JSON.stringify({alice:2}))});
async function main(){await new Promise(r=>fixture.listen(0,'127.0.0.1',r));const port=18081;backend=spawn(path.join(root,'dist','traffic-manager-lite'+(process.platform==='win32'?'.exe':'')),[],{cwd:root,windowsHide:true,env:{...process.env,TML_LISTEN:'127.0.0.1:'+port,TML_DB_PATH:path.join(tmp,'traffic.db'),TML_BACKUP_DIR:path.join(tmp,'backups'),TML_CONFIG_ROOT:path.join(tmp,'configs'),TML_ADMIN_PASSWORD:password,TML_SECURE_COOKIE:'false',TML_COLLECT_INTERVAL:'1h',TML_ALLOWED_TARGETS:''}});backend.stderr.on('data',b=>logs+=b);backend.stdout.on('data',b=>logs+=b);const base='http://127.0.0.1:'+port;for(let i=0;i<100;i++){try{if((await fetch(base+'/api/v1/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}assert.equal((await fetch(base+'/api/v1/health')).status,200,logs);
 browser=await chromium.launch({headless:true});const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>failures.push(e.message));page.on('console',m=>{if(m.type()==='error')failures.push(m.text())});await page.goto(base);await page.locator('[name=password]').fill(password);await page.getByRole('button',{name:'登录管理后台'}).click();await page.waitForURL(base+'/');await page.getByRole('heading',{name:'流量总览',exact:true}).waitFor();await page.locator('.stats-grid').waitFor();await page.screenshot({path:path.join(output,'dashboard-empty.png'),fullPage:true});
 await page.goto(base+'/#instances');await page.getByRole('button',{name:'添加服务器'}).click();await page.locator('#fields [name=name]').fill('浏览器测试服务器');await page.locator('#fields [name=address]').fill('127.0.0.1');await page.locator('#edit-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);await page.locator('[data-action=edit-server]').click();await page.locator('#fields [name=name]').fill('已编辑测试服务器');await page.locator('#edit-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);await page.getByText('已编辑测试服务器',{exact:true}).waitFor();await page.getByRole('button',{name:'添加服务器'}).click();await page.locator('#fields [name=name]').fill('待删除服务器');await page.locator('#edit-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);await page.locator('[data-action=delete-server][data-id="2"]').click();await page.locator('#edit-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);assert.equal(await page.getByText('待删除服务器',{exact:true}).count(),0);await page.getByRole('button',{name:'接入实例'}).click();await page.locator('#fields [name=name]').fill('Hysteria2 · 测试夹具');await page.locator('#fields [name=core_type]').selectOption('hysteria2');await page.locator('#fields [name=api_endpoint]').fill('http://127.0.0.1:'+fixture.address().port);await page.locator('#fields [name=config_path]').fill(path.join(tmp,'configs','hy.yaml'));await page.locator('#edit-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);await page.getByRole('button',{name:'检测 API',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('API 连通：Available'));await page.getByRole('button',{name:'采集',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('采集已完成'));counter++;await page.getByRole('button',{name:'采集',exact:true}).click();await page.getByRole('button',{name:'采集',exact:true}).waitFor({state:'visible'});
 await page.goto(base+'/#nodes');await page.getByRole('button',{name:'扫描配置'}).click();await page.getByRole('button',{name:'编辑',exact:true}).waitFor();await page.getByRole('button',{name:'编辑',exact:true}).click();await page.locator('#fields [name=address]').fill('example.com');await page.locator('#fields [name=port]').fill('443');await page.locator('#fields [name=sni]').fill('example.com');await page.locator('#edit-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
 await page.goto(base+'/#subscriptions');await page.getByRole('button',{name:'创建订阅'}).click();await page.locator('#fields [name=name]').fill('测试订阅');await page.locator('#fields [name=format]').selectOption('singbox');await page.locator('#node-choices input').check();await page.locator('#edit-form [type=submit]').click();await page.locator('#token-dialog').waitFor({state:'visible'});const subURL=await page.locator('#token-url').inputValue();const response=await fetch(subURL);assert.equal(response.status,200);assert.equal((await response.json()).outbounds[0].type,'hysteria2');await page.getByRole('button',{name:'已保存'}).click();await page.getByRole('button',{name:'重新生成地址'}).click();await page.locator('#token-dialog').waitFor({state:'visible'});assert.equal((await fetch(subURL)).status,404);await page.getByRole('button',{name:'已保存'}).click();
 for(const width of [360,768,1440]){await page.setViewportSize({width,height:1000});for(const target of ['dashboard','instances','traffic','online','nodes','subscriptions','settings','diagnostics']){await page.goto(base+'/#'+target);await page.waitForFunction(()=>!document.querySelector('#content').textContent.includes('正在加载'));await page.waitForTimeout(100);const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(sizes.scroll<=sizes.width,`${target} at ${width}: overflow ${JSON.stringify(sizes)}`);if(target==='dashboard')await page.screenshot({path:path.join(output,`dashboard-fixture-${width}.png`),fullPage:true})}}
 await page.setViewportSize({width:360,height:800});await page.goto(base+'/#instances');await page.getByRole('button',{name:'接入实例'}).click();await page.locator('#editor').waitFor({state:'visible'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'切换主题'}).click();assert.ok(await page.locator('body').evaluate(x=>x.classList.contains('dark')));await page.screenshot({path:path.join(output,'mobile-dark.png'),fullPage:true});assert.deepEqual(failures,[]);console.log('PASS: login, server CRUD, instance authorization without env whitelist, real HTTP fixture collection, discovery, overrides, subscription generation/rotation, 24 page+viewport checks, mobile forms, dark theme, no browser errors');
}
main().catch(e=>{console.error(e);console.error(logs);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(backend)backend.kill();fixture.close();/* Keep test DB in OS temp for inspection; it is never production data. */});
