/* Real official Xray + real manager UI. All processes/configurations are isolated test resources. */
const {spawn,execFileSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.TML_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),binary=process.env.TML_TEST_XRAY;if(!binary)throw new Error('TML_TEST_XRAY required');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'tml-real-xray-ui-')),out=path.join(root,'dist','ui-verification');fs.mkdirSync(out,{recursive:true});
let browser;const processes=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){return new Promise(r=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p))})})}
async function main(){const [apiPort,inboundPort,httpPort]=await Promise.all([port(),port(),port()]);const endpoint='localhost:'+apiPort,config=path.join(tmp,'xray.json');
const cfg={log:{loglevel:'warning'},api:{tag:'api',listen:'127.0.0.1:'+apiPort,services:['HandlerService','StatsService']},stats:{},policy:{levels:{'0':{statsUserUplink:true,statsUserDownlink:true,statsUserOnline:false}}},inbounds:[{tag:'real-offline-clients',listen:'127.0.0.1',port:inboundPort,protocol:'vless',settings:{clients:Array.from({length:10},(_,i)=>({email:'real-user-'+(i+1),id:crypto.randomUUID()})),decryption:'none'},streamSettings:{network:'tcp'}}],outbounds:[{protocol:'freedom'}]};fs.writeFileSync(config,JSON.stringify(cfg));
const version=execFileSync(binary,['version'],{encoding:'utf8'}).split(/\r?\n/)[0];fs.writeFileSync(config+'.version.json',JSON.stringify({api_endpoint:endpoint,method:'controlled_xray_version',output:version,observed_at:new Date().toISOString(),config_sha256:crypto.createHash('sha256').update(fs.readFileSync(config)).digest('hex')}));
processes.push(spawn(binary,['run','-config',config],{windowsHide:true,stdio:'ignore'}));
const password='real-xray-ui-password-123456';processes.push(spawn(path.join(root,'dist','traffic-manager-lite'+(process.platform==='win32'?'.exe':'')),[],{windowsHide:true,stdio:'ignore',env:{...process.env,TML_LISTEN:'127.0.0.1:'+httpPort,TML_DB_PATH:path.join(tmp,'traffic.db'),TML_CONFIG_ROOT:tmp,TML_BACKUP_DIR:path.join(tmp,'backups'),TML_ADMIN_PASSWORD:password,TML_SECURE_COOKIE:'false',TML_ALLOWED_TARGETS:'',TML_COLLECT_INTERVAL:'1h',TML_COLLECT_TIMEOUT:'2s'}}));
const base='http://127.0.0.1:'+httpPort;for(let i=0;i<100;i++){try{if((await fetch(base+'/api/v1/health')).ok)break}catch{}await sleep(100)}
const auth='Basic '+Buffer.from('admin:'+password).toString('base64');async function api(route,method='GET',data){const r=await fetch(base+'/api/v1/'+route,{method,headers:{Authorization:auth,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw new Error(JSON.stringify(b));return b}
await api('servers','POST',{name:'隔离官方 Xray 测试',address:'localhost',enabled:true});await api('instances','POST',{server_id:1,name:'官方 Xray · 10 个离线用户',core_type:'xray',api_endpoint:endpoint,config_path:config,enabled:true});
for(let i=0;i<100;i++){const rows=await api('xray/diagnostics');if(rows[0]?.report)break;await sleep(100)}
await api('instances/1/collect','POST',{});const assets=await api('instances/1/clients');assert.equal(assets.filter(c=>c.source==='runtime_api'&&c.present).length,10);const online=await api('online');assert.equal(online.length,10);assert.ok(online.every(o=>o.status==='unknown'));
browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('[name=password]').fill(password);await page.getByRole('button',{name:'登录管理后台'}).click();await page.waitForURL(base+'/');await page.goto(base+'/#diagnostics');await page.getByRole('button',{name:'立即诊断'}).waitFor();await page.getByText('26.3.27',{exact:true}).waitFor();
await page.getByRole('button',{name:'立即诊断'}).click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('只读诊断完成'));await page.getByRole('button',{name:'查看诊断历史'}).click();await page.locator('#diagnostic-history-1 p').first().waitFor();
for(const width of [360,768,1440]){await page.setViewportSize({width,height:1000});await page.locator('.diagnostic-check summary').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'xray-diagnostics-real-'+width+'.png'),fullPage:true})}
const diagnostic=await api('instances/1/diagnostics');const serialized=JSON.stringify(diagnostic);for(const u of cfg.inbounds[0].settings.clients)assert.ok(!serialized.includes(u.id),'UUID leaked');assert.deepEqual(errors,[]);
console.log('PASS: real official Xray UI; 10 offline runtime Clients; Stats empty; Online Unknown; actual executable version; manual diagnostics/history; credential redaction; desktop/tablet/mobile');}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();for(const p of processes)p.kill()});
