// Read-only wire projection of V2Fly v5.53.0 ObservatoryService.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: internal/proto/v2flyobserve/observe.proto

package observepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOutboundStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboundStatusRequest) Reset() {
	*x = GetOutboundStatusRequest{}
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboundStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboundStatusRequest) ProtoMessage() {}

func (x *GetOutboundStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboundStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOutboundStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v2flyobserve_observe_proto_rawDescGZIP(), []int{0}
}

func (x *GetOutboundStatusRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetOutboundStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ObservationResult     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboundStatusResponse) Reset() {
	*x = GetOutboundStatusResponse{}
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboundStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboundStatusResponse) ProtoMessage() {}

func (x *GetOutboundStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboundStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOutboundStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v2flyobserve_observe_proto_rawDescGZIP(), []int{1}
}

func (x *GetOutboundStatusResponse) GetStatus() *ObservationResult {
	if x != nil {
		return x.Status
	}
	return nil
}

type ObservationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []*OutboundStatus      `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationResult) Reset() {
	*x = ObservationResult{}
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationResult) ProtoMessage() {}

func (x *ObservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationResult.ProtoReflect.Descriptor instead.
func (*ObservationResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_v2flyobserve_observe_proto_rawDescGZIP(), []int{2}
}

func (x *ObservationResult) GetStatus() []*OutboundStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Only retain the boolean; errors, targets and outbound tags are not diagnostic data.
type OutboundStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundStatus) Reset() {
	*x = OutboundStatus{}
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundStatus) ProtoMessage() {}

func (x *OutboundStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v2flyobserve_observe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundStatus.ProtoReflect.Descriptor instead.
func (*OutboundStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_v2flyobserve_observe_proto_rawDescGZIP(), []int{3}
}

func (x *OutboundStatus) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

var File_internal_proto_v2flyobserve_observe_proto protoreflect.FileDescriptor

const file_internal_proto_v2flyobserve_observe_proto_rawDesc = "" +
	"\n" +
	")internal/proto/v2flyobserve/observe.proto\x12\"v2ray.core.app.observatory.command\",\n" +
	"\x18GetOutboundStatusRequest\x12\x10\n" +
	"\x03Tag\x18\x01 \x01(\tR\x03Tag\"j\n" +
	"\x19GetOutboundStatusResponse\x12M\n" +
	"\x06status\x18\x01 \x01(\v25.v2ray.core.app.observatory.command.ObservationResultR\x06status\"_\n" +
	"\x11ObservationResult\x12J\n" +
	"\x06status\x18\x01 \x03(\v22.v2ray.core.app.observatory.command.OutboundStatusR\x06status\"&\n" +
	"\x0eOutboundStatus\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive2\xa9\x01\n" +
	"\x12ObservatoryService\x12\x92\x01\n" +
	"\x11GetOutboundStatus\x12<.v2ray.core.app.observatory.command.GetOutboundStatusRequest\x1a=.v2ray.core.app.observatory.command.GetOutboundStatusResponse\"\x00B<Z:traffic-manager-lite/internal/proto/v2flyobserve;observepbb\x06proto3"

var (
	file_internal_proto_v2flyobserve_observe_proto_rawDescOnce sync.Once
	file_internal_proto_v2flyobserve_observe_proto_rawDescData []byte
)

func file_internal_proto_v2flyobserve_observe_proto_rawDescGZIP() []byte {
	file_internal_proto_v2flyobserve_observe_proto_rawDescOnce.Do(func() {
		file_internal_proto_v2flyobserve_observe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v2flyobserve_observe_proto_rawDesc), len(file_internal_proto_v2flyobserve_observe_proto_rawDesc)))
	})
	return file_internal_proto_v2flyobserve_observe_proto_rawDescData
}

var file_internal_proto_v2flyobserve_observe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_v2flyobserve_observe_proto_goTypes = []any{
	(*GetOutboundStatusRequest)(nil),  // 0: v2ray.core.app.observatory.command.GetOutboundStatusRequest
	(*GetOutboundStatusResponse)(nil), // 1: v2ray.core.app.observatory.command.GetOutboundStatusResponse
	(*ObservationResult)(nil),         // 2: v2ray.core.app.observatory.command.ObservationResult
	(*OutboundStatus)(nil),            // 3: v2ray.core.app.observatory.command.OutboundStatus
}
var file_internal_proto_v2flyobserve_observe_proto_depIdxs = []int32{
	2, // 0: v2ray.core.app.observatory.command.GetOutboundStatusResponse.status:type_name -> v2ray.core.app.observatory.command.ObservationResult
	3, // 1: v2ray.core.app.observatory.command.ObservationResult.status:type_name -> v2ray.core.app.observatory.command.OutboundStatus
	0, // 2: v2ray.core.app.observatory.command.ObservatoryService.GetOutboundStatus:input_type -> v2ray.core.app.observatory.command.GetOutboundStatusRequest
	1, // 3: v2ray.core.app.observatory.command.ObservatoryService.GetOutboundStatus:output_type -> v2ray.core.app.observatory.command.GetOutboundStatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_v2flyobserve_observe_proto_init() }
func file_internal_proto_v2flyobserve_observe_proto_init() {
	if File_internal_proto_v2flyobserve_observe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v2flyobserve_observe_proto_rawDesc), len(file_internal_proto_v2flyobserve_observe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_v2flyobserve_observe_proto_goTypes,
		DependencyIndexes: file_internal_proto_v2flyobserve_observe_proto_depIdxs,
		MessageInfos:      file_internal_proto_v2flyobserve_observe_proto_msgTypes,
	}.Build()
	File_internal_proto_v2flyobserve_observe_proto = out.File
	file_internal_proto_v2flyobserve_observe_proto_goTypes = nil
	file_internal_proto_v2flyobserve_observe_proto_depIdxs = nil
}
