'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',page='',trendDays=7,saveEditor=null,loadVersion=0;
let diagnosticServer='',diagnosticInstance='',diagnosticCore='';
const titles={diagnostics:['核心 API 诊断','Clients、Stats、Online 独立检测；诊断只读，不重置流量。'],dashboard:['流量总览','掌握流量变化，了解每一个核心的运行状态。'],instances:['核心实例','连接你的代理核心，独立采集每一个实例。'],traffic:['用户流量','按自然日查询持久汇总，归档后历史流量依然完整。'],online:['在线监控','真实在线与最近活跃分别展示，过期数据不会被当作离线。'],nodes:['代理节点','从只读配置发现节点，补充真实客户端连接参数。'],subscriptions:['订阅管理','为每个用户生成专属订阅，认证凭据保持隔离。'],settings:['系统设置','查看运行参数，管理归档与数据库备份。']};
function bytes(n){n=Number(n)||0;const u=['B','KiB','MiB','GiB','TiB','PiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return [n.toFixed(i?2:0),u[i]]}function fmt(n){return bytes(n).join(' ')}
function date(v){return v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'尚无数据'}
function badge(text,kind=''){return `<span class="badge ${esc(kind)}">${esc(text)}</span>`}function empty(text='暂无数据',hint='接入实例并完成采集后，数据会显示在这里。'){return `<div class="empty"><strong>${esc(text)}</strong>${esc(hint)}</div>`}
async function api(path,method='GET',data){const r=await fetch('/api/v1/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data===undefined?undefined:JSON.stringify(data)});if(r.status===401){location.href='/login.html';throw new Error('请登录')}const text=await r.text();let v;try{v=JSON.parse(text)}catch{v={error:text}}if(!r.ok)throw new Error(v.error||'请求失败');return v}
function notice(message){$('#notice').textContent=message;$('#notice').hidden=!message}
function table(headers,rows,kind=""){return rows.length?`<div class="table-wrap ${esc(kind)}"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>`<td data-label="${esc(headers[i])}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty()}
function stat(label,n,symbol,note){const [v,u]=bytes(n);return `<div class="card stat"><div class="stat-top">${label}<span class="stat-symbol">${symbol}</span></div><div class="stat-value">${v}<small>${u}</small></div><div class="stat-note">${note}</div></div>`}
function chart(history,days){const recent=history.slice(-days);if(!recent.length)return empty('还没有流量趋势','首次采集建立基线，后续流量变化会形成趋势。');const width=Math.min(740,Math.max(280,innerWidth-72)),span=width-78;const max=Math.max(1,...recent.map(x=>Math.max(Number(x.upload),Number(x.download))));const point=(row,index,key)=>`${52+index*span/Math.max(1,recent.length-1)},${180-Number(row[key])/max*145}`;let svg=`<svg viewBox="0 0 ${width} 225" role="img" aria-label="每日上传下载流量趋势">`;for(let i=0;i<4;i++){const y=180-i*48;svg+=`<line class="chart-grid" x1="52" y1="${y}" x2="${width-22}" y2="${y}"/><text class="chart-text" x="0" y="${y+3}">${fmt(max*i/3)}</text>`}for(const [key,color]of [['download','#6960e7'],['upload','#15977e']]){const points=recent.map((r,i)=>point(r,i,key)).join(' ');svg+=`<polyline points="${points}" fill="none" stroke="${color}" stroke-width="2.5" stroke-linejoin="round"/>`;recent.forEach((r,i)=>{const [x,y]=point(r,i,key).split(',');svg+=`<circle cx="${x}" cy="${y}" r="3" fill="${color}"><title>${esc(r.date)} ${key==='upload'?'上传':'下载'} ${fmt(r[key])}</title></circle>`})}recent.forEach((r,i)=>{if(i===0||i===recent.length-1||i%Math.ceil(recent.length/6)===0)svg+=`<text class="chart-text" x="${52+i*span/Math.max(1,recent.length-1)}" y="210" text-anchor="middle">${esc(r.date.slice(5))}</text>`});return `<div class="chart-wrap">${svg}</svg></div><div class="chart-legend"><span><i class="legend-dot"></i>客户端下载</span><span><i class="legend-dot green"></i>客户端上传</span></div>`}
function instanceRows(insts){return insts.map(i=>[`${esc(i.name)}<small>${esc(i.api_endpoint||i.control_endpoint||i.clash_endpoint)}</small>`,`${badge(i.core_type)}<small>运行版本：${esc(i.detected_version||'Unknown')}</small>`,i.enabled&&i.server_enabled?badge(i.last_error?'采集异常':i.last_collected_at?'已连接':'等待采集',i.last_error?'red':i.last_collected_at?'green':'gray'):badge(i.enabled?'服务器停用':'已停用','gray'),date(i.last_collected_at),`<small>${esc(i.capabilities.map(c=>`${c.metric}: ${c.status}${c.reason?' ('+c.reason+')':''}`).join(' · '))}</small>${esc(i.last_error)}`,`<button data-action="collect" data-id="${i.id}" ${i.enabled&&i.server_enabled?'':'disabled'}>采集</button><button data-action="test-instance" data-id="${i.id}">检测 API</button><button data-action="open-diagnostics" data-id="${i.id}">API 诊断</button><button data-action="edit-instance" data-id="${i.id}">编辑</button>`])}
async function dashboard(){const d=await api('dashboard'),online=d.online.filter(x=>x.status==='online'),active=new Set(d.online.filter(x=>x.active).map(x=>x.user_id)),cores=d.cores,total=cores.reduce((s,x)=>s+Number(x.upload)+Number(x.download),0);return `<div class="stats-grid">${stat('今日总流量',Number(d.today.upload)+Number(d.today.download),'↗','统计时区 '+esc(d.timezone))}${stat('今日上传',d.today.upload,'↑','<b>↑</b> 客户端上传至服务器')}${stat('今日下载',d.today.download,'↓','<b>↓</b> 服务器发送至客户端')}${stat('本月总流量',Number(d.month.upload)+Number(d.month.download),'◷','历史累计 '+fmt(Number(d.all.upload)+Number(d.all.download)))}</div><div class="summary-strip"><div class="card mini-stat"><span class="stat-symbol">▣</span><div><strong>${d.instances.length}</strong><small>核心实例</small></div></div><div class="card mini-stat"><span class="stat-symbol">◎</span><div><strong>${new Set(online.map(x=>x.user_id)).size}</strong><small>真实在线用户 · 仅支持的 API</small></div></div><div class="card mini-stat"><span class="stat-symbol">↯</span><div><strong>${active.size}</strong><small>最近活跃用户</small></div></div></div><div class="grid-two"><section class="card panel"><div class="panel-heading"><h2>流量趋势</h2><div class="segmented"><button data-action="trend" data-days="7" class="${trendDays===7?'selected':''}">近 7 天</button><button data-action="trend" data-days="30" class="${trendDays===30?'selected':''}">近 30 天</button></div></div>${chart(d.history,trendDays)}</section><section class="card panel"><div class="panel-heading"><h2>核心流量分布</h2><small class="muted">历史累计 · 用户统计</small></div>${cores.length?cores.map(c=>`<div class="core-row"><div><span>${esc(c.dimension)}</span><span>${fmt(Number(c.upload)+Number(c.download))}</span></div><svg width="100%" height="8" role="img" aria-label="流量占比"><rect width="100%" height="6" rx="3" fill="#6960e710"/><rect width="${total?(Number(c.upload)+Number(c.download))/total*100:0}%" height="6" rx="3" fill="#6960e7"/></svg></div>`).join(''):empty('暂无核心流量','不使用模拟数据。')}</section></div><section class="card panel"><div class="panel-heading"><h2>实例运行状态</h2><a href="#instances">管理实例 →</a></div>${table(['实例','核心','状态','最近采集','统计能力 / 错误','操作'],instanceRows(d.instances))}</section>`}
async function instances(){const [is,servers,settings]=await Promise.all([api('instances'),api('servers'),api('settings')]);return `<section class="card panel"><div class="toolbar"><h2>核心实例 <span class="muted">${is.length}</span></h2><div><button data-action="new-server">添加服务器</button> <button class="primary" data-action="new-instance">＋ 接入实例</button></div></div>${table(['实例','核心','状态','最近采集','统计能力 / 错误','操作'],instanceRows(is))}</section><section class="card panel spacer"><div class="panel-heading"><h2>服务器</h2></div>${table(['名称','VPS 地址 / 标识','状态','操作'],servers.map(s=>[esc(s.name),esc(s.address),badge(s.enabled?'启用':'停用',s.enabled?'green':'gray'),`<button data-action="edit-server" data-id="${s.id}">编辑</button><button data-action="delete-server" data-id="${s.id}" data-name="${esc(s.name)}">删除</button>`]))}</section><div class="info-box">${settings.target_policy==='restricted'?'严格模式：实例地址须符合部署白名单。':'实例授权模式：后台保存 API 地址即可接入，无需逐个配置环境变量。'} 服务器地址仅用于 VPS 标识，实际采集使用实例 API 地址。采集只读访问核心 API。版本字段为管理员声明；sing-box 原生 API 可探测真实版本、实例流量和当前连接，兼容 API 的用户统计按实际计数器探测。</div>`}
function trafficFilters(instances,servers){return `<div class="filters"><select id="range" aria-label="时间范围"><option value="today">今日</option><option value="cycle">当前采集周期</option><option value="yesterday">昨日</option><option value="7d">近 7 天</option><option value="30d">近 30 天</option><option value="month">本月</option><option value="last_month">上月</option><option value="all">历史累计</option><option value="custom">自定义</option></select><input id="from" type="date" aria-label="开始日期"><input id="to" type="date" aria-label="结束日期"><select id="server-filter" aria-label="服务器"><option value="">全部服务器</option>${servers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><select id="instance-filter" aria-label="实例"><option value="">全部实例</option>${instances.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select><input id="search" placeholder="搜索用户" aria-label="搜索用户"><select id="sort" aria-label="排序"><option value="total">总流量排序</option><option value="upload">上传排序</option><option value="download">下载排序</option></select><button data-action="filter">查询</button></div>`}
async function traffic(){const [instances,servers]=await Promise.all([api('instances'),api('servers')]);return `<section class="card panel"><div class="toolbar"><h2>用户流量</h2>${trafficFilters(instances,servers)}</div><div id="traffic-table">正在加载…</div></section><section class="card panel spacer"><div class="toolbar"><h2>维度汇总</h2><div class="filters"><select id="aggregation-dimension" aria-label="汇总维度"><option value="server">服务器</option><option value="instance">实例</option><option value="inbound">Inbound</option><option value="protocol">协议</option><option value="node">节点</option><option value="core">核心</option></select><select id="aggregation-scope" aria-label="计数器层级"><option value="user">用户计数器</option><option value="inbound">Inbound 计数器</option><option value="instance">实例计数器</option></select><button data-action="aggregate">查询汇总</button></div></div><div id="aggregation-table"></div><small class="muted">计数器层级分别查询，避免同一流量重复累计；无法唯一归属的节点显示为未归属。</small></section><section class="card panel spacer"><div class="panel-heading"><h2>用户历史趋势</h2><span id="user-trend-name" class="muted">点击用户的趋势按钮</span></div><div id="user-trend">${empty('选择一个用户','所有流量来自后端持久汇总。')}</div></section>`}
function trafficQuery(){return new URLSearchParams({server_id:$('#server-filter').value,instance_id:$('#instance-filter').value,range:$('#range').value,from:$('#range').value==='custom'?$('#from').value:'',to:$('#range').value==='custom'?$('#to').value:''})}
async function filterTraffic(){await aggregateTraffic();const q=trafficQuery(),[totals,users]=await Promise.all([api('traffic/summary?dimension=user&'+q),api('users?search='+encodeURIComponent($('#search').value))]);const map=new Map(totals.map(x=>[String(x.dimension),x]));const rows=users.map(u=>({...u,...(map.get(String(u.id))||{upload:0,download:0})}));const sort=$('#sort').value;rows.sort((a,b)=>sort==='total'?Number(b.upload)+Number(b.download)-Number(a.upload)-Number(a.download):Number(b[sort])-Number(a[sort]));$('#traffic-table').innerHTML=table(['用户','上传','下载','总流量','统计观测','最近活跃','操作'],rows.map(u=>[esc(u.display_name),fmt(u.upload),fmt(u.download),fmt(Number(u.upload)+Number(u.download)),esc(JSON.parse(u.stats_states||'[]').map(s=>({zero:'真实零计数',present:'计数器存在',not_generated:'尚未生成统计项',unknown:'统计未知',reset_baseline:'重启/回退后新基线'}[s.state]||s.state)+' · 实例 #'+s.instance_id).join('；')||'无 Xray 观测记录'),date(u.last_active_at),`<button data-action="user-trend" data-id="${u.id}" data-name="${esc(u.display_name)}">趋势</button><button data-action="rename-user" data-id="${u.id}" data-name="${esc(u.display_name)}">改名</button><button data-action="merge-user" data-id="${u.id}">关联身份</button>`]))}
async function online(){const rows=await api('online'),labels={online:'真实在线',offline:'离线',stale:'数据过期',unsupported:'不支持',unknown:'等待探测'};return `<section class="card panel"><div class="panel-heading"><h2>在线与最近活跃</h2><small class="muted">每 10 秒自动刷新</small></div>${table(['用户 / 身份','核心 / 实例','inbound','真实在线','连接指标','最近活跃','更新'],rows.map(o=>[`${esc(o.display_name)}<small>${esc(o.core_user_key)}</small>`,`${badge(o.core_type)}<small>${esc(o.instance_name)}</small>`,esc(o.inbound_tag||'无法归属'),badge(labels[o.status]||o.status,o.status==='online'?'green':o.status==='stale'?'red':'gray'),o.count===null?'—':`${o.count} ${esc(o.kind||'')}<small>${esc(o.basis||(o.ips||[]).join(', '))}</small>`,`${badge(o.active?'最近活跃':'无近期变化',o.active?'green':'gray')}<small>${date(o.last_active_at)}</small>`,date(o.updated_at)]))}</section><div class="info-box">device 为客户端实例，ip 为在线 IP；两者均不等于 TCP 连接数。最近活跃依据流量增量。API 不支持与采集数据过期分别显示。</div>`}
async function nodes(){const rows=await api('nodes');return `<section class="card panel"><div class="toolbar"><h2>发现的节点</h2><button class="primary" data-action="scan">↻ 扫描配置</button></div>${table(['节点 / inbound','协议 / 传输','客户端地址','完整性','订阅兼容性','操作'],rows.map(({node:n,compatibility:c})=>[`${esc(n.profile.name)}<small>${esc(n.inbound_tag)} · 用户 #${n.user_id}</small>`,`${badge(n.profile.protocol)}<small>${esc(n.profile.transport)}</small>`,`${esc(n.profile.address||'待补充')}:${n.profile.port||'—'}<small>服务端监听 ${n.profile.listen_port||'—'}</small>`,`${badge(n.complete?'完整':'不完整',n.complete?'green':'red')}<small>${esc(n.issues.join('；'))}</small>`,Object.entries(c).map(([k,v])=>`${badge(k,v?'gray':'green')}<small>${esc(v||'支持')}</small>`).join(''),`<button data-action="edit-node" data-id="${n.id}">编辑</button><button data-action="toggle-node" data-id="${n.id}" data-enabled="${n.profile.enabled}">${n.profile.enabled?'停用':'启用'}</button>`]))}</section><div class="info-box">客户端地址与端口必须手动确认。人工覆盖不会被扫描覆盖。停用仅影响订阅，不修改代理服务。</div>`}
async function subscriptions(){const rows=await api('subscriptions');return `<section class="card panel"><div class="toolbar"><h2>用户订阅</h2><button class="primary" data-action="new-sub">＋ 创建订阅</button></div>${table(['名称','格式','所属用户','节点','状态','更新时间','操作'],rows.map(s=>[esc(s.name),badge(s.format),'#'+s.user_id,JSON.parse(s.node_ids||'[]').length,badge(s.enabled?'启用':'禁用',s.enabled?'green':'gray'),date(s.updated_at),`<button data-action="edit-sub" data-id="${s.id}">编辑</button><button data-action="rotate" data-id="${s.id}" data-format="${s.format}">重新生成地址</button><button data-action="toggle-sub" data-id="${s.id}">${s.enabled?'禁用':'启用'}</button>`]))}</section><div class="info-box">订阅地址是访问凭据。创建或重新生成后可复制；服务端只保存 Token 哈希。兼容性限制请在节点管理查看。</div>`}
async function settings(){const s=await api('settings');const labels={collect_interval:'采集间隔',active_window:'最近活跃窗口',timezone:'聚合时区',raw_retention_days:'明细保留天数',archive_enabled:'自动归档',log_level:'日志级别',target_policy:'API 访问策略'};return `<section class="card panel"><div class="panel-heading"><h2>运行配置</h2><button data-action="edit-settings">修改参数</button></div><div class="settings-list">${Object.entries(labels).map(([k,v])=>`<div><span class="muted">${v}</span><strong>${esc(k==='target_policy'?(s[k]==='restricted'?'严格白名单':'后台实例授权'):String(s[k]))}</strong></div>`).join('')}</div><div class="info-box">${esc(s.configuration)}</div></section><section class="card panel spacer"><div class="panel-heading"><h2>数据库维护</h2></div><p class="muted">明细保留 30 天，小时和日汇总长期保留。归档先验证一致性，再在事务内删除明细。</p><div class="toolbar"><button data-action="archive">执行安全归档</button><button data-action="backup">创建一致性备份</button></div></section>`}
const views={dashboard,instances,traffic,online,nodes,subscriptions,settings,diagnostics};
async function render(silent=false){const next=location.hash.slice(1)||'dashboard';page=views[next]?next:'dashboard';const v=++loadVersion;const [title,subtitle]=titles[page];$('#title').textContent=title;$('#subtitle').textContent=subtitle;$('#crumb').textContent=title;document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#sidebar').classList.remove('open');if(!silent)$('#content').innerHTML=empty('正在加载','正在读取服务端数据…');try{const html=await views[page]();if(v!==loadVersion)return;$('#content').innerHTML=html;if(page==='traffic')await filterTraffic();$('#clock').textContent='更新于 '+new Date().toLocaleTimeString('zh-CN',{hour12:false})}catch(e){if(v===loadVersion){notice(e.message);if(!silent)$('#content').innerHTML=empty('数据加载失败','点击刷新重试。')}}}
function field(name,label,value='',type='text',options){if(type==='select')return `<label>${esc(label)}<select name="${name}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;if(type==='checkbox')return `<label class="wide"><input name="${name}" type="checkbox" ${value?'checked':''}>${esc(label)}</label>`;return `<label>${esc(label)}<input name="${name}" type="${type}" autocomplete="${type==='password'?'new-password':'off'}" value="${esc(value)}" ${type==='number'?'min="0"':''}></label>`}
function edit(title,html,save){$('#edit-title').textContent=title;$('#fields').innerHTML=html;$('#form-error').textContent='';saveEditor=save;$('#editor').showModal()}
function values(form){const d=Object.fromEntries(new FormData(form));form.querySelectorAll('input[type=checkbox]').forEach(x=>d[x.name]=x.checked);form.querySelectorAll('input[type=number]').forEach(x=>d[x.name]=Number(x.value));return d}
async function serverEditor(id){const s=id?await api('servers/'+id):{enabled:true};edit(id?'编辑服务器':'添加服务器',field('name','服务器名称',s.name)+field('address','VPS 地址 / 标识（可选）',s.address)+field('enabled','启用采集',s.enabled,'checkbox')+'<p class="info-box wide">地址仅用于展示和归组，不是统计 API 地址。停用会暂停所属实例的新采集，历史数据保留。</p>',d=>api(id?'servers/'+id:'servers',id?'PATCH':'POST',d))}
async function instanceEditor(id){const [insts,servers]=await Promise.all([api('instances'),api('servers')]);if(!servers.length)throw new Error('请先添加服务器');const i=insts.find(x=>x.id===Number(id))||{enabled:true,core_type:'xray',server_id:servers[0].id};edit(id?'编辑实例':'接入核心实例',field('name','实例名称',i.name)+field('server_id','服务器',i.server_id,'select',servers.map(x=>[x.id,x.name]))+field('core_type','核心类型',i.core_type,'select',['xray','v2fly','singbox','hysteria2'].map(x=>[x,x]))+field('api_endpoint','统计 API 地址',i.api_endpoint)+field('control_endpoint','sing-box 原生 gRPC 地址（可选）',i.control_endpoint)+field('clash_endpoint','sing-box Clash HTTP 地址（可选）',i.clash_endpoint)+field('clash_secret','Clash Secret（留空保留；未设置时使用 API Secret）','','password')+field('api_secret','API Secret（留空保留）','','password')+field('config_path','只读配置完整路径',i.config_path)+field('version','声明的核心版本',i.version)+field('enabled','启用采集',i.enabled,'checkbox'),async d=>{d.server_id=Number(d.server_id);if(d.core_type!=='singbox'){d.control_endpoint='';d.clash_endpoint='';delete d.clash_secret}if(id&&!d.api_secret)delete d.api_secret;if(id&&!d.clash_secret)delete d.clash_secret;await api(id?'instances/'+id:'instances',id?'PATCH':'POST',d)});const toggle=()=>{for(const name of ['control_endpoint','clash_endpoint','clash_secret']){$('#fields [name='+name+']').closest('label').hidden=$('#fields [name=core_type]').value!=='singbox'}};$('#fields [name=core_type]').onchange=toggle;toggle()}
async function nodeEditor(id){const all=await api('nodes'),n=all.find(x=>x.node.id===id).node,p=n.profile;let html='';for(const [key,label,type]of [['name','节点名称'],['address','客户端地址 / 优选 IP'],['port','客户端端口','number'],['sni','SNI'],['host','WebSocket Host'],['path','WebSocket Path'],['service_name','gRPC ServiceName'],['public_key','Reality 公钥'],['short_id','Reality Short ID'],['fingerprint','指纹'],['flow','Flow'],['uuid','客户端 UUID'],['password','客户端密码','password'],['method','加密方法'],['sort','排序','number']])html+=field(key,label,p[key],type);html+=field('transport','传输',p.transport,'select',[['tcp','TCP'],['ws','WebSocket'],['grpc','gRPC'],['xhttp','XHTTP（当前生成器会过滤）']])+field('tls','TLS',p.tls,'checkbox')+field('enabled','启用订阅输出',p.enabled,'checkbox');edit('编辑节点连接参数',html,d=>api('nodes/'+id,'PATCH',d))}
async function subEditor(id){const [subs,users,nodes]=await Promise.all([api('subscriptions'),api('users'),api('nodes')]);if(!users.length)throw new Error('请先扫描配置或完成用户流量采集');const s=subs.find(x=>x.id===Number(id))||{enabled:true,format:'v2ray',user_id:users[0].id,node_ids:'[]'},selected=JSON.parse(s.node_ids);const html=field('name','订阅名称',s.name)+field('format','客户端格式',s.format,'select',[['v2ray','v2rayN / Base64'],['mihomo','Mihomo YAML'],['singbox','sing-box JSON']])+field('user_id','所属用户',s.user_id,'select',users.map(x=>[x.id,x.display_name+' #'+x.id]))+field('enabled','启用订阅',s.enabled,'checkbox')+'<label class="wide">选择节点（按显示顺序）<div class="checklist" id="node-choices"></div></label>';edit(id?'编辑订阅':'创建用户订阅',html,async d=>{d.user_id=Number(d.user_id);d.node_ids=[...$('#node-choices').querySelectorAll(':checked')].map(x=>x.value);delete d.node;const res=await api(id?'subscriptions/'+id:'subscriptions',id?'PATCH':'POST',d);if(res.token)showToken(d.format,res.token)});const update=()=>{$('#node-choices').innerHTML=nodes.filter(x=>x.node.user_id===Number($('#fields [name=user_id]').value)).map(({node:n})=>`<label><input name="node" type="checkbox" value="${n.id}" ${selected.includes(n.id)?'checked':''}>${esc(n.profile.name)} ${n.complete?'':'（不完整）'}</label>`).join('')||'<p class="muted">此用户没有已发现节点</p>'};$('#fields [name=user_id]').addEventListener('change',update);update()}
function showToken(format,token){$('#token-url').value=location.origin+'/sub/'+format+'/'+token;$('#token-dialog').showModal()}
async function aggregateTraffic(){const q=trafficQuery();q.set('dimension',$('#aggregation-dimension').value);q.set('scope',$('#aggregation-scope').value);const rows=await api('traffic/summary?'+q);$('#aggregation-table').innerHTML=table(['维度','上传','下载','总流量'],rows.map(x=>[esc(x.dimension||'未归属'),fmt(x.upload),fmt(x.download),fmt(Number(x.upload)+Number(x.download))]));}
const actions={
 'open-diagnostics':async b=>{diagnosticInstance=b.dataset.id;diagnosticServer='';diagnosticCore='';location.hash='diagnostics';if(page==='diagnostics')await render()},
 'diagnostic-filter':async()=>{diagnosticCore=$('#diagnostic-core').value;diagnosticServer=$('#diagnostic-server').value;diagnosticInstance=$('#diagnostic-instance').value;await render(true)},
 diagnose:async b=>{await api('instances/'+b.dataset.id+'/diagnostics','POST',{});notice('只读诊断完成，流量基线和统计未修改')},
 'diagnostic-history':async b=>{const rows=await api('instances/'+b.dataset.id+'/diagnostics/history');$('#diagnostic-history-'+b.dataset.id).innerHTML=rows.map(row=>{const r=JSON.parse(row.report_json);return `<p>${esc(date(row.checked_at))} · ${esc(row.trigger)} · 运行版本 ${esc(r.version)} · ${esc(r.health.map(h=>h.collector+': '+h.status).join(' / '))}</p>`}).join('')||'尚无诊断历史'},
 'test-instance':async b=>{const r=await api('instances/'+b.dataset.id+'/test','POST',{});notice('API 连通：'+r.report.connected+'；认证：'+r.report.authentication+'；'+r.records+' 项统计结果。详情见 API 诊断；未修改流量基线')},
 collect:async b=>{await api('instances/'+b.dataset.id+'/collect','POST',{});notice('采集已完成')},
 'new-server':()=>serverEditor(),'edit-server':b=>serverEditor(b.dataset.id),'delete-server':b=>edit('删除服务器','<p class="info-box wide">确认删除服务器“'+esc(b.dataset.name)+'”？有关联实例时会拒绝删除；请先编辑实例迁移归属。</p>',()=>api('servers/'+b.dataset.id,'DELETE')),
 'new-instance':()=>instanceEditor(),'edit-instance':b=>instanceEditor(b.dataset.id),
 scan:async()=>{const rows=await api('discovery/scan','POST',{});notice(rows.map(x=>'实例 #'+x.instance_id+': '+(x.error||'发现 '+x.nodes+' 个节点')).join('；')||'请先在实例中配置只读配置路径')},
 'edit-node':b=>nodeEditor(b.dataset.id),'toggle-node':b=>api('nodes/'+b.dataset.id,'PATCH',{enabled:b.dataset.enabled!=='true'}),
 'new-sub':()=>subEditor(),'edit-sub':b=>subEditor(b.dataset.id),rotate:async b=>{const r=await api('subscriptions/'+b.dataset.id+'/rotate','POST',{});showToken(b.dataset.format,r.token)},
 'toggle-sub':async b=>{const s=(await api('subscriptions')).find(x=>x.id===Number(b.dataset.id));await api('subscriptions/'+s.id,'PATCH',{name:s.name,format:s.format,user_id:s.user_id,enabled:!s.enabled,node_ids:JSON.parse(s.node_ids)})},
 aggregate:()=>aggregateTraffic(),trend:b=>{trendDays=Number(b.dataset.days)},filter:()=>filterTraffic(),
 'user-trend':async b=>{const h=await api('traffic/history?user_id='+b.dataset.id+'&'+trafficQuery());$('#user-trend').innerHTML=chart(h,30);$('#user-trend-name').textContent=b.dataset.name},
 'rename-user':b=>edit('修改用户名称',field('display_name','显示名称',b.dataset.name),d=>api('users/'+b.dataset.id,'PATCH',d)),
 'merge-user':async b=>{const ids=await api('identities');edit('关联核心身份',field('identity_id','将此核心身份关联到当前用户','','select',ids.map(x=>[x.id,`${x.instance_name} · ${x.core_user_key}（用户 #${x.user_id}）`]))+'<p class="info-box wide">历史统计随身份归属更新；原用户订阅不会继续输出已转移节点。</p>',d=>api('users/'+b.dataset.id+'/identities','POST',{identity_id:Number(d.identity_id)}))},
 archive:async()=>{const r=await api('maintenance/archive','POST',{});notice('归档校验成功，清理 '+r.deleted+' 条明细')},backup:async()=>{const r=await api('maintenance/backup','POST',{});notice('一致性备份已创建：'+r.backup)},
 'edit-settings':async()=>{const s=await api('settings');edit('修改运行参数',field('collect_interval','采集间隔（如 10s）',s.collect_interval)+field('active_window','活跃窗口（如 60s）',s.active_window)+field('log_level','日志级别',s.log_level,'select',['debug','info','warn','error'].map(x=>[x,x]))+field('archive_enabled','每日自动归档',s.archive_enabled,'checkbox')+'<p class="info-box wide">保存到 SQLite，重启 Traffic Manager Lite 后生效。30 天保留和聚合时区固定。</p>',d=>api('settings','PATCH',d))}
};
$('#content').addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;notice('');b.disabled=true;try{await actions[action](b);if(!$('#editor').open&&!['filter','user-trend','aggregate','diagnostic-history'].includes(action))await render(true)}catch(err){notice(err.message)}finally{b.disabled=false}});
$('#edit-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{await saveEditor(values(e.target));$('#editor').close();await render(true)}catch(err){$('#form-error').textContent=err.message}finally{b.disabled=false}});
$('#close-dialog').onclick=$('#cancel-dialog').onclick=()=>$('#editor').close();$('#close-token').onclick=()=>{$('#token-dialog').close();$('#token-url').value=''};$('#copy-token').onclick=async()=>{try{await navigator.clipboard.writeText($('#token-url').value);$('#copy-token').textContent='已复制'}catch{$('#token-url').select();$('#copy-token').textContent='请手动复制'}};
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#refresh').onclick=()=>render();$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark');$('#logout').onclick=async()=>{await api('auth/logout','POST',{});location.href='/login.html'};window.addEventListener('hashchange',()=>render());
(async()=>{try{const s=await api('auth/session');csrf=s.csrf;await render();setInterval(()=>{if((page==='online'||page==='dashboard')&&!$('#editor').open&&!document.hidden)render(true)},10000)}catch(e){notice(e.message)}})();

function diagnosticStatus(status){const symbols={Available:'✓',Healthy:'✓',Unsupported:'—',Disabled:'⊘',AuthenticationFailed:'🔒',Unreachable:'✕',Error:'✕',Unknown:'?'};return badge((symbols[status]||'?')+' '+status,status==='Available'||status==='Healthy'?'green':['Error','AuthenticationFailed','Unreachable'].includes(status)?'red':'gray')}
function diagnosticTable(headers,rows){return table(headers,rows,"diagnostic-table")}
async function diagnostics(){
 const q=new URLSearchParams({server_id:diagnosticServer,instance_id:diagnosticInstance,core_type:diagnosticCore});const [rows,servers,instances]=await Promise.all([api('cores/diagnostics?'+q),api('servers'),api('instances')]);
 let html=`<section class="card panel"><div class="filters"><select id="diagnostic-core" aria-label="诊断核心类型"><option value="">全部核心</option>${['xray','hysteria2','singbox','v2fly'].map(c=>`<option value="${c}" ${c===diagnosticCore?'selected':''}>${esc(c)}</option>`).join('')}</select><select id="diagnostic-server" aria-label="诊断服务器"><option value="">全部服务器</option>${servers.map(s=>`<option value="${s.id}" ${String(s.id)===diagnosticServer?'selected':''}>${esc(s.name)}</option>`).join('')}</select><select id="diagnostic-instance" aria-label="诊断实例"><option value="">全部实例</option>${instances.filter(i=>!diagnosticCore||i.core_type===diagnosticCore).map(i=>`<option value="${i.id}" ${String(i.id)===diagnosticInstance?'selected':''}>${esc(i.name)}</option>`).join('')}</select><button data-action="diagnostic-filter">查询</button></div></section>`;
 if(!rows.length)return html+empty('暂无核心实例','在核心实例中接入后自动执行首次诊断。');
 for(const i of rows){const r=i.report||{version:'Unknown',build_info:'Unknown',version_source:'unavailable',connected:'Unknown',config_source:'尚未诊断',checks:[],health:[]};const [assets,health]=await Promise.all([api('instances/'+i.instance_id+'/clients'),api('instances/'+i.instance_id+'/health')]);
 html+=`<section class="card panel spacer"><div class="toolbar"><h2>${esc(i.server_name)} / ${esc(i.instance_name)}</h2><button class="primary" data-action="diagnose" data-id="${i.instance_id}">立即诊断</button></div><div class="settings-list">${[['核心类型',i.core_type],['API 检测体系',r.api_types?.join(' / ')||'尚未探测'],['认证状态',r.authentication||'Unknown'],['运行版本',r.version],['版本检测说明',r.version_reason||(r.version==='Unknown'?'未取得可信版本证据':'已取得版本证据')],['构建信息',r.build_info],['版本证据',r.version_source],['统计 API 地址',i.api_endpoint||'未配置'],...(i.core_type==='singbox'?[['原生 gRPC 地址',i.control_endpoint||i.api_endpoint||'未配置'],['Clash HTTP 地址',i.clash_endpoint||'未配置']]:[]),['API 连通',r.connected],['最近成功流量采集',date(i.last_collected_at)],['最近诊断',date(r.checked_at)],['配置来源',r.config_source]].map(([k,v])=>`<div><span class="muted">${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div><h3>采集健康（独立于 API 能力）</h3>${diagnosticTable(['采集器','健康','结果','最近成功','说明'],health.map(h=>[esc(h.collector),diagnosticStatus(h.status),h.result_count,date(h.success_at),esc(h.summary)]))}<h3>本次只读诊断观测（不改写采集健康）</h3>${diagnosticTable(['类别','状态','数量','原因'],r.health.map(h=>[esc(h.collector),diagnosticStatus(h.status),h.count,esc(h.summary||'请求成功')]))}<h3>API 能力 / 调用详情</h3><div class="diagnostic-checks">${r.checks.map(c=>`<details class="diagnostic-check"><summary><strong>${esc(c.group)} · ${esc(c.api)}</strong> ${diagnosticStatus(c.status)}</summary><dl>${[['实际方法',c.method],['检测依据',c.evidence||'实际只读请求 / 官方 schema'],['响应摘要',c.response_summary||c.count+' 项（不含凭据）'],['适用版本',c.applicable_version||r.version],['请求参数',c.params],['请求次数',c.requests||0],['结果数量',c.count],['耗时',c.duration_ms+' ms'],['错误代码',c.code],['原因',c.reason||'请求成功'],['必要配置',c.required],['建议',c.advice||'无需处理'],['检查时间',date(c.checked_at)]].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></details>`).join('')}</div><h3>Clients 用户资产 / 来源差异</h3><p class="muted">${i.core_type==='xray'?'运行时与文件分别保存；HMAC 比较已验证的凭据字段，不证明完整配置一致。':'完整资产来自只读配置，文件不保证与运行时一致。Stats/Online 仅关联已有身份，不能代替 Clients。'} missing/unknown 不等于零流量或离线。</p>${diagnosticTable(['Inbound','用户标识','协议','来源','资产','来源比对','Stats','Online / 判据'],assets.map(c=>[esc(c.inbound_tag),esc(c.email||'无 Email（不能关联流量）'),esc(c.protocol),esc(c.source),c.present?'已配置 / 最近成功观测':'此来源已移除',esc(({source_only:'仅此来源',metadata_mismatch:'协议/level 不一致',credential_mismatch:'身份凭据/Flow 不一致',matching_verified_fields:'已验证字段一致',credential_comparison_unknown:'凭据无法可靠比对',anonymous_unlinked:'匿名资产未关联'})[c.comparison]||c.comparison),esc(c.stats_state||'unknown'),`${esc(c.online_state||'unknown')}<small>${esc(c.online_basis||'尚未可靠检测')}</small>`]))}<button data-action="diagnostic-history" data-id="${i.instance_id}">查看诊断历史</button><div id="diagnostic-history-${i.instance_id}"></div></section>`;
 }
 return html;
}
